### ISSUE TITLE
Noduim wallet out of sync

### ISSUE THREAD

**Issue by Swissuser** [nodiumproject/Wallets#2]
Have installed Zerocoin wallet on my mac. It's still out of sync after 1 day. 
No blockchain downloaded. 
I've tried to desactivate antivirus, stop firewall. 
Nothing changes
Someone to help me ?

**Comment by crypto-hazo** [comment]
If you have the issue trouble connecting to our nodes, please add these manually. They have been checked and verified today. Add to your wallet, wallet.conf or masternode, nodium.conf:
addnode=104.40.156.80:6250
addnode=137.117.169.85:6250
addnode=104.46.46.149:6250
addnode=23.101.130.219:6250
addnode=40.121.17.246:6250
addnode=45.77.85.68:6250
addnode=207.246.103.185:6250
addnode=149.28.65.232:6250
addnode=63.211.111.160:6250
addnode=45.77.186.130:6250
addnode=149.28.126.35:6250
addnode=45.76.42.84:6250
addnode=199.247.27.31:6250
addnode=209.250.227.223:6250
addnode=217.69.4.153:6250

**Comment by Swissuser** [comment]
Worked. Many thanks !
